import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	metadataBase: new URL("https://acknowledged-pgp-three-brand.trycloudflare.com/"),
	openGraph: {
		title: "Codely Lego",
		description: "El mejor de la historia",
		images: [
			{
				url: "https://api.microlink.io?url=https://codely.com&screenshot=true&meta=false&embed=screenshot.url",
			},
		],
	},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
